# Generated by Django 4.2.20 on 2026-03-08 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_turnociudadano_auditoria_configuracion'),
    ]

    operations = []
