# Generated by Django 4.2.20 on 2026-05-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=True)),
                ('rol', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCambioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevo_email', models.EmailField(max_length=254, verbose_name='Nuevo email')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de confirmación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('expirado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_email', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de cambio de email',
                'verbose_name_plural': 'Solicitudes de cambio de email',
                'indexes': [models.Index(fields=['user', 'confirmado'], name='users_solic_user_id_8f3fb4_idx'), models.Index(fields=['creado'], name='users_solic_creado_6858a6_idx')],
            },
        ),
    ]
