# Generated by Django 4.2.30 on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programas", "0019_tipodispositivo_umbral_ocupacion_amarillo_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="admision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cama__isnull", False), ("estado", "ALOJADO")),
                fields=("cama",),
                name="admision_una_cama_alojada",
            ),
        ),
    ]
