# Generated by Django 4.2.20 on 2026-04-14 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0034_ciudadano_campos_perfil_ampliado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legajoinstitucional',
            old_name='responsable_sedronar',
            new_name='responsable_asignado',
        ),
    ]